name: Build IPT LaTeX document
run-name: Build Document by @${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
        env:
          TEXINPUTS: ".:./packages/biblatex-abnt//:./classes//:"
        run: |
          echo Passo executado com sucesso.
